BaSP-MR-82: Create modals
BaSP-m2023/nico-megarocket-app pull request #1
Opened 2023-05-29 17:43 UTC by FrancoLelli

I created success and confirm modals

2023-05-29 21:25 UTC, CristianLotorto approved these changes
it seems to be ok!

2023-05-29 23:46 UTC, CristianLotorto approved these changes

2023-05-29 23:55 UTC, ticilicarzze approved these changes

2023-05-30 00:24 UTC, NicoCagnina requested changes

2023-05-30 00:24 UTC, NicoCagnina commented on src/Components/Modals/ModalConfirm/index.js
> +            fn();
Can we give this a better naming? Maybe something like onConfirm

2023-05-30 00:24 UTC, NicoCagnina commented on src/Components/Modals/ToastError/toastError.module.css
> +  min-width: 250px; /* Set a default minimum width */
Can we remove this comments?

2023-05-30 01:48 UTC, NicoCagnina approved these changes

2023-05-30 12:54 UTC, merged