BaSP-MR-186: Component Cards - Activity in Members
BaSP-m2023/nico-megarocket-app pull request #101
Opened 2023-06-18 21:11 UTC by MaateoC

I added Cards that demostrate the activities which should be created within the Members tab

2023-06-19 00:29 UTC, CristianLotorto approved these changes
Looks great Mate! nice work!

2023-06-19 02:21 UTC, IvanJukonis requested changes
Changes on this component are being on discussion.

2023-06-20 14:42 UTC, YhanahiRosenthal commented on src/Components/Users/Member/activities/Cards/cards.module.css
> +  text-decoration: none;
here it has two ";" and next lines i think no work

2023-06-20 14:42 UTC, YhanahiRosenthal requested changes
i commented something!

2023-06-20 19:38 UTC, IvanJukonis approved these changes

2023-06-20 23:49 UTC, YhanahiRosenthal approved these changes
Good job!

2023-06-20 23:52 UTC, merged