BaSP-MR-187: Activities cards modals
BaSP-m2023/nico-megarocket-app pull request #109
Opened 2023-06-20 14:15 UTC by flordimonaco

Modals done for every activity :)

2023-06-20 14:26 UTC, YhanahiRosenthal commented on src/Components/Users/Member/modals/bodybuildingcard.jsx
> +        </p>
you should make a single component for all activities, because it brings data from DB

2023-06-20 14:28 UTC, YhanahiRosenthal requested changes
i commented something on bodybiuldingcard

2023-06-20 19:07 UTC, YhanahiRosenthal approved these changes
Good job!

2023-06-20 19:40 UTC, IvanJukonis approved these changes

2023-06-20 19:42 UTC, merged

2023-06-21 00:26 UTC, flordimonaco commented
![](https://github.trello.services/images/mini-trello-icon.png) [MODAL - Activity Card](https://trello.com/c/fxfWRjbB/187-modal-activity-card)