BaSP-MR-78: add/edit forms
BaSP-m2023/nico-megarocket-app pull request #11
Opened 2023-05-31 01:01 UTC by flordimonaco

2023-05-31 19:47 UTC, CristianLotorto commented on src/Components/Subscriptions/Table/TableSubscription.jsx
> +      console.log(subscriptionUpdated);
this console.log should not be here

2023-05-31 20:08 UTC, CristianLotorto commented on src/Components/Subscriptions/Table/TableSubscription.jsx
> +          <button
methods on this button triggers an infinite loop

2023-05-31 20:09 UTC, CristianLotorto requested changes
take a look at the comments

2023-05-31 21:41 UTC, NicoCagnina requested changes
please add a description

2023-05-31 21:41 UTC, NicoCagnina commented on src/Components/Subscriptions/Table/TableSubscription.jsx
> +      console.log(subscriptionUpdated);
remove this console log

2023-06-02 19:19 UTC, FrancoLelli requested changes
Add validation. So, we render a text in case there are no active subscriptions. Good Job!

2023-06-02 19:19 UTC, FrancoLelli commented on src/Components/Subscriptions/Table/Index.jsx
> +      <TableSubscriptions
```suggestion
            {!subscription.length ? (
        <p>No active Subscriptions</p>
      ) : (
        <TableSubscriptions  subscription={subscription} setSubscription={setSubscription} deleteSubscription{deleteSubscription}/>
      )}
```

2023-06-03 19:08 UTC, FrancoLelli approved these changes

2023-06-03 19:15 UTC, CristianLotorto approved these changes

2023-06-03 19:36 UTC, cbaleani approved these changes
Looks good!

2023-06-03 19:39 UTC, merged