BaSP-MR-70: Add and Edit Form in Super Admin
BaSP-m2023/nico-megarocket-app pull request #13
Opened 2023-05-31 02:05 UTC by IvanJukonis

Hello, I have submitted the PR for ticket number 70. This ticket required the development of the Update and Create functionalities for Super Admins, displaying a modal to confirm the modification. Additionally, I had to add the functionality of showing the Creation form, but enabled for performing updates.

All the requirements of the ticket have been resolved.

Due to the List and Delete functionalities created in ticket 69, which were also under my responsibility, not being merged, they were implemented in the first commit in order to develop this PR. By submitting both PRs, I will be able to resolve the conflicts easily.

Functionalities to add: The form was not styled due to lack of time.

2023-05-31 02:06 UTC, IvanJukonis commented
![](https://github.trello.services/images/mini-trello-icon.png) [SUPER ADMIN - Add/edit form](https://trello.com/c/kiWU79Cd/70-super-admin-add-edit-form)

2023-05-31 03:52 UTC, FrancoLelli requested changes
I think you should delete the comment, but, its ok!! Nice Job!

2023-05-31 03:52 UTC, FrancoLelli commented on src/Components/SuperAdmins/index.jsx
> +      // eslint-disable-next-line no-unused-vars
```suggestion
```

2023-05-31 15:59 UTC, CristianLotorto commented on src/Components/SuperAdmins/index.jsx
> +      console.log(JSON.stringify(updatedData));
try to delete console.log

2023-05-31 21:43 UTC, NicoCagnina requested changes

2023-05-31 21:43 UTC, NicoCagnina commented on src/Components/SuperAdmins/index.js
why did you remove this file?

2023-06-01 00:07 UTC, IvanJukonis commented on src/Components/SuperAdmins/index.js
I changed the file index.js to index.jsx in order to follow the instructions of the weekly class. Im not sure why I deleted it, on my other PR I just changed the termination.

2023-06-02 12:09 UTC, IvanJukonis commented on src/Components/SuperAdmins/index.jsx
> +      console.log(JSON.stringify(updatedData));
Same as responded to Franco.

2023-06-02 12:18 UTC, FrancoLelli approved these changes

2023-06-02 17:45 UTC, cbaleani commented on package.json
The package.json should not be changed.

2023-06-02 17:45 UTC, cbaleani commented on package-lock.json
Changes in the package-lock.json shouldn't be pushed

2023-06-02 19:36 UTC, FrancoLelli requested changes
Change names, please!!

2023-06-02 19:36 UTC, FrancoLelli commented on src/Components/SuperAdmins/Form/index.jsx
> +import ModalsConfirmation from '../../Modals/ModalConfirm';
```suggestion
import ModalConfirm from '../../Modals/ModalConfirm';
```

2023-06-02 19:36 UTC, FrancoLelli commented on src/Components/SuperAdmins/Form/index.jsx
> +        <ModalsConfirmation
```suggestion
        <ModalConfirm
```

2023-06-02 21:35 UTC, FrancoLelli approved these changes

2023-06-02 21:38 UTC, cbaleani approved these changes
Looks good!

2023-06-02 21:38 UTC, merged

2023-06-03 05:15 UTC, GleViDe commented
### 2nd Testing Results
Ivan please check the following bug report. For more details, go to the ticket 'MR-114' in Trello: [MR-114](https://trello.com/c/KywYrFTi/114-super-admin-cant-add-new-super-admin)

Tested locally on https://nico-megarocket-app-git-feature-mr-70superadmin-add-43525f-basp.vercel.app/super-admins
Test result: Failed

Bug found:
After filling out the form to add a new Super Admin and left clicking on the "Agregar Super Admin" button, nothing happens.