BaSP-MR-66: Add and edit form
BaSP-m2023/nico-megarocket-app pull request #14
Opened 2023-05-31 02:06 UTC by ticilicarzze

## Description

This pull request implements features that let you add and edit a table with a form. 

## Checklist

- [ ] Create add/edit form including necessary fields
- [ ] On edit functionality should show previous info
- [ ] Success message for confirmation edit and add actions
- [ ] Success message for confirmation edit and add actions

2023-05-31 02:12 UTC, FrancoLelli approved these changes
Nice Job!!

2023-05-31 03:43 UTC, CristianLotorto requested changes
nice job! But you pushed .gitignore and package-lock.json :/. Lets fix that

2023-05-31 21:45 UTC, NicoCagnina requested changes

2023-05-31 21:45 UTC, NicoCagnina commented on .gitignore
> +package.json
we should not add this to the gitignore

2023-05-31 21:45 UTC, NicoCagnina commented on .gitignore
> +package-lock.json
we should not add this to git ignore

2023-05-31 21:45 UTC, NicoCagnina commented on src/Components/Admins/Table/table.module.css
> +  /* border: 1px solid black; */
remove this comment

2023-06-02 18:32 UTC, iaracriscenti approved these changes
🚀

2023-06-02 18:56 UTC, merged

2023-06-03 14:18 UTC, GleViDe commented
### 2nd Testing Results
Tested locally on https://nico-megarocket-app-git-admin-mr-66add-edit-form-basp.vercel.app/admins
Test result: Passed

Great job!!