BaSP-MR-65: List a table of admins and delete petition functionality
BaSP-m2023/nico-megarocket-app pull request #2
Opened 2023-05-30 03:28 UTC by maurojjzz

## Pull Request

### Description

My[ Trello's ticket](https://trello.com/c/21aMjyND) describe that i had to list the admins that are created on a given database within a table i which i also had to add extras buttons: 'Edit' , 'Delete' and 'Create Admin' but only the delete button would have functionality with it petition.

The class tutor 'Nicolas Cagnina' and this week TL 'Cristian Lotorto' gave me permission to create individual Modals instead of using the globals one (at the time i made this PR those weren't available). With that being said i made a component Modals within the Admin component and within Modals component i created other two components 'ModalDelete' that gives you the option of confirm the deletion and  the component 'ModalDeleteConfirmation' that shows a confirmation in case you actually press delete on last component.

### Changes Made
On Admins component
- index.js and its css added
- created Table component that contains an index.js and its css file
- created Modals component that contains ModalDelete and ModalDeleteConfirmation components
- ModalDelete compontent that contains an index.js and its css file
- ModalDeleteConfirmation compontent that contains an index.js and its css file

### Checklist

- [x] Show table with list: Columns: full name (first name + last name), email, phone, city
- [x]  Add delete row functionality
- [x]  Add actions icons (delete, edit) for each row
- [x] Warning message for delete
- [x] Success message for confirm
- [x] Add "add new admin" button

2023-05-30 03:30 UTC, maurojjzz commented
![](https://github.trello.services/images/mini-trello-icon.png) [ADMIN - List/delete table](https://trello.com/c/21aMjyND/65-admin-list-delete-table)

2023-05-30 03:49 UTC, CristianLotorto requested changes
U've pushed .gitignore and package-lock. Lets start for fixing that :/

2023-05-30 16:43 UTC, CristianLotorto approved these changes
It's seems to be all ok. Good job!

2023-05-30 17:29 UTC, NicoCagnina requested changes

2023-05-30 17:29 UTC, NicoCagnina commented on src/Components/Admins/Modals/ModalDeleteConfirmation/ModalDeleteConfirmation.js
> +  const cerrar = () => {
Since all the code is in english, this should be too. Besides, we could give it a more descriptive name like closeModal

2023-05-30 19:25 UTC, IvanJukonis approved these changes
I couldnt find any inconsistency in the code or any lack of tidiness. It has all the required functionalities and no bugs or errors. Nice work!!

2023-05-31 21:06 UTC, NicoCagnina approved these changes

2023-05-31 21:14 UTC, merged

2023-06-03 14:23 UTC, GleViDe commented
### 2nd Testing Results

I couldn't test it locally on https://nico-megarocket-app-git-admin-mr-65list-delete-table-basp.vercel.app/admins , because you had not yet merged the functionality of add new admin before doing this PR.

Tested locally on http://localhost:3000/admins
Test result: Passed