BaSP-MR-123: Delete functionality BUG
BaSP-m2023/nico-megarocket-app pull request #35
Opened 2023-06-05 04:07 UTC by IvanJukonis

The current PR is related to ticket 123. To resolve it, the TRAINERS component needs to have the DELETE functionality implemented correctly.

All the requirements listed in the ticket have been completed.

Problem: The DELETE function uses the ID stored in the TRAINERS state. When a trainer is added, the generated ID of the response is not saved in the TRAINERS state. Therefore, when performing the ADD action without refreshing the page, all trainers stored in the TRAINERS state do not have an ID, which makes the DELETE functionality impossible to use.

Solution: Every time an ADD action is performed on trainers, the ID is obtained from the response, and the complete trainer is stored within the TRAINERS state.

2023-06-05 04:12 UTC, IvanJukonis commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] -Trainer - Error Delete](https://trello.com/c/76HQ5YNF/123-bug-trainer-error-delete)

2023-06-05 20:56 UTC, maurojjzz requested changes

2023-06-05 20:56 UTC, maurojjzz commented on src/Components/Trainers/TableTrainers/index.jsx
> +    console.log(id);
delete this console.log

2023-06-05 20:56 UTC, maurojjzz commented on src/Components/Trainers/FormTrainers/index.jsx
>      console.log(validateForm());
delete this console.log

2023-06-06 02:11 UTC, maurojjzz approved these changes
nice work

2023-06-06 02:32 UTC, merged