BaSP-MR-79: List a table of trainers and delete petition functionality
BaSP-m2023/nico-megarocket-app pull request #4
Opened 2023-05-30 16:40 UTC by maurojjzz

## Pull Request

### Description

My [Trello's ticket](https://trello.com/c/WnEW2EAr)  describes that i had to list the trainer that are created on a given database within a table i which i also had to add extras buttons: 'Edit' and  'Delete'  but only the delete button would have functionality with it petition.

I used the global Modals on my table and made a little change on it (with consent of the creator). 

### Changes Made
On Trainers component
- index.js and its css added.
- created Table component that contains an index.js .
- created a table.module.css which i used to give styles to the table.
- added buttons on table and gave them styles as well.

### Checklist

- [x] Show table with list: Columns: full name (first name + last name), email, phone, city, is active, salary
- [x]  Add delete row functionality
- [x]  Add actions icons (delete, edit) for each row
- [x] Warning message for delete
- [x] Success message for confirm

2023-05-30 16:51 UTC, maurojjzz commented
![](https://github.trello.services/images/mini-trello-icon.png) [TRAINER - List/delete table](https://trello.com/c/WnEW2EAr/79-trainer-list-delete-table)

2023-05-30 17:35 UTC, NicoCagnina requested changes

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +            //firstName="firstName"
remove this comment

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +            //lastName="lastName"
remove this comment

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +            //dni="dni"
remove this comment

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +            //phone="phone"
remove this comment

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +            //email="email"
remove this comment

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +            //city="city"
remove this comment

2023-05-30 17:35 UTC, NicoCagnina commented on src/Components/Trainers/TableTrainers/index.jsx
> +// import ToastError from '../Modals/ToastError/index';
remove this comment

2023-05-30 18:17 UTC, FrancoLelli approved these changes
Nice Job Mauro!

2023-05-31 03:28 UTC, CristianLotorto approved these changes
great job!

2023-05-31 21:08 UTC, NicoCagnina requested changes

2023-05-31 21:08 UTC, NicoCagnina commented on src/Components/Trainers/FormTrainers/index.jsx
> +  const onChargeInput = (e) => {
should be change not charge

2023-06-01 22:32 UTC, NicoCagnina approved these changes

2023-06-01 22:39 UTC, merged