BaSP-MR-103: Members Form
BaSP-m2023/nico-megarocket-app pull request #48
Opened 2023-06-06 22:09 UTC by Ginoboca1

Members Form Create
Members Form Edit

2023-06-06 22:15 UTC, FrancoLelli approved these changes

2023-06-06 22:23 UTC, YhanahiRosenthal commented on src/Components/Members/Form/MembersForm.js
> +import React, { useState, useEffect } from 'react';
you should remove import component repeated

2023-06-06 22:30 UTC, YhanahiRosenthal commented on src/Components/Members/Form/form.module.css
> +} */
you should delete all unnecessary comments

2023-06-06 22:31 UTC, FrancoLelli requested changes
Change path!!

2023-06-06 22:31 UTC, FrancoLelli commented on src/Components/Layout/index.js
> +          <Route path="/members/membersForm/:id?" component={MembersForm} />
```suggestion
          <Route path="/members/form/:id?" component={MembersForm} />
```

2023-06-06 22:55 UTC, FrancoLelli approved these changes

2023-06-06 22:55 UTC, merged

2023-06-07 13:30 UTC, Barbimillan commented
Gino, in the second test I found this bugs: 
Description: I click on the edit option and the title to the form says Add Member, and then the box modal to confirm also says Are you sure you want to add this member? Then when I confirm the edition appear a Box modal with member deleted! before the modal member edited

Steps:

Step 1 - Open home page.

Step 2 - Go to Member.

Step 3 - Click to edit member.

Step 4 - Complete the form.

Step 5 - Click submit

Expected result: Title Edit Member. When I submit a Box modal Are you sure you want to edit this member?, and then to click ok a box modal that says member edited successfully.

Actual result:  The form has the title Add member, the box model says Are you sure you want to add this member?, and then to click ok appear a box modal that says member deleted successfully!