BaSP-MR-104: Implements table components
BaSP-m2023/nico-megarocket-app pull request #49
Opened 2023-06-06 22:20 UTC by YhanahiRosenthal

Table component implemented

2023-06-06 22:30 UTC, FrancoLelli requested changes
Delete comment!

2023-06-06 22:30 UTC, FrancoLelli commented on src/Components/Subscriptions/index.js
> +        // arrayAndObject={arrayAndObject}
```suggestion

```

2023-06-06 22:43 UTC, CristianLotorto approved these changes
fix the commented line, the rest is ok!

2023-06-07 02:47 UTC, maurojjzz commented
![](https://github.trello.services/images/mini-trello-icon.png) [SUBSCRIPTION - Table](https://trello.com/c/iayq47wG/104-subscription-table)

2023-06-08 00:31 UTC, merged