BaSP-MR-69: List a table of super admins and delete petition functionality
BaSP-m2023/nico-megarocket-app pull request #5
Opened 2023-05-30 18:51 UTC by IvanJukonis

Hello, I have submitted the PR for ticket number 69. This ticket required the development of a table listing the Super Admin component for its resolution. Each row corresponding to a superadmin should contain a delete button (with its corresponding functionality) and an edit button (without functionality). Finally, the creation of a button to add a super admin is required, as well as the creation of confirmation modals for the delete function.

**All the requirements of the ticket have been resolved.**

2023-05-30 19:30 UTC, IvanJukonis commented
![](https://github.trello.services/images/mini-trello-icon.png) [SUPER ADMIN - List/delete table](https://trello.com/c/C8r6fRY6/69-super-admin-list-delete-table)

2023-05-30 21:54 UTC, CristianLotorto requested changes
there's an issue in delete functionality

2023-05-30 22:37 UTC, IvanJukonis commented
> there's an issue in delete functionality

The issue is not found in the delete but in the add functionality. This has already been discussed with Cristian and we reached the agreement that the error will be mentioned in my next PR, where a solution will be sought. Although the delete functionality may be affected by this error, there is nothing to correct.

2023-05-30 22:39 UTC, CristianLotorto approved these changes

2023-05-31 01:20 UTC, maurojjzz approved these changes
everything looks great

2023-05-31 21:09 UTC, NicoCagnina requested changes

2023-06-01 00:10 UTC, IvanJukonis commented on src/Components/SuperAdmins/index.js
Oh i did the same on my other PR, I wanted to change the JS termination of the file into JSX.

2023-06-02 16:19 UTC, cbaleani approved these changes
Looks great!

2023-06-02 16:21 UTC, merged