BaSP-MR-107: Implementation of shared Components into Form.
BaSP-m2023/nico-megarocket-app pull request #54
Opened 2023-06-07 01:05 UTC by IvanJukonis

Here is my pull request regarding ticket number 107, where the implementation of global components was required within the SuperAdmins form.

**IMPORTANT**: Since I am responsible for both components (table and form), the first commit is a copy of the PR related to ticket 106. This was done because I am not allowed to create a branch from another branch, and I needed the previous work to resolve this ticket. Since I am handling both PRs, any conflicts arising from this will be resolved promptly.

Therefore, I recommend not making any corrections to the changes made in the first commit.

2023-06-07 01:06 UTC, IvanJukonis commented
![](https://github.trello.services/images/mini-trello-icon.png) [SUPERADMINS - Form](https://trello.com/c/hPIGpFzo/107-superadmins-form)

2023-06-07 01:25 UTC, FrancoLelli requested changes
Nice Job, but resolve that comments!

2023-06-07 01:25 UTC, FrancoLelli commented on src/Components/SuperAdmins/Form/index.jsx
> +import { useHistory, useParams } from 'react-router-dom/cjs/react-router-dom.min';
```suggestion

```

2023-06-07 01:25 UTC, FrancoLelli commented on src/Components/SuperAdmins/Form/index.jsx
> +import { useLocation } from 'react-router-dom';
```suggestion
import { useLocation, useHistory, useParams } from 'react-router-dom';
```

2023-06-07 20:24 UTC, FrancoLelli requested changes

2023-06-07 20:24 UTC, FrancoLelli commented on package.json
> +    "node": "16.8.0",
set 18.x version

2023-06-07 20:31 UTC, FrancoLelli approved these changes

2023-06-07 23:10 UTC, maurojjzz approved these changes
good job

2023-06-07 23:31 UTC, merged

2023-06-09 11:52 UTC, IvanJukonis commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] Super Admin - The list is not displayed](https://trello.com/c/jCURDTfk/146-bug-super-admin-the-list-is-not-displayed)