BaSP-MR-80: post and put methos in Trainer
BaSP-m2023/nico-megarocket-app pull request #8
Opened 2023-05-30 23:24 UTC by Emanuel-Lamberti

**Description**
My [Trello's ticket](https://trello.com/c/3CMwFXFf/80-trainer-add-edit-form) describes that i had to should do conditional rendering based on a momentary state. 
To do this, develop methods to add and edit (by id) the coaches that will later be added to the table.

_I used the global Modals on my table and made a little change on it (with consent of the creator)._

**Changes Made**
On Trainers component

- -index.js and its css added.
- -created Table component that contains an index.js .
- -created a table.module.css which i used to give styles to the table.
- -add button on table and gave them styles as well.

**Checklist**

- [ ]  -Create add/edit form including necessary fields
- [ ]  -On edit functionality should show previous info
- [ ]  -Success message for confirmation edit and add actions
- [ ]  -Error message for edit and create actions
- [ ]  -Add "add new admin" button

2023-05-31 00:10 UTC, FrancoLelli requested changes
Ema, nice Job, but i think you should delete comments!!

2023-05-31 00:10 UTC, FrancoLelli commented on src/Components/Trainers/FormEditTrainers/FormEditTrainer.jsx
> +// eslint-disable-next-line no-unused-vars
```suggestion

```

2023-05-31 00:10 UTC, FrancoLelli commented on src/Components/Trainers/FormTrainers/index.jsx
> +  // eslint-disable-next-line no-unused-vars
```suggestion
 
```

2023-05-31 00:10 UTC, FrancoLelli commented on src/Components/Trainers/TableTrainers/index.jsx
> +// eslint-disable-next-line no-unused-vars
```suggestion
```

2023-05-31 01:41 UTC, FrancoLelli approved these changes

2023-05-31 01:43 UTC, flordimonaco commented
> Ema, nice Job, but i think you should delete comments!!

I agree with fran!

2023-05-31 03:34 UTC, CristianLotorto requested changes
good code Ema, but you pushed .gitignore, package-lock.json and package.json :/

2023-05-31 15:41 UTC, CristianLotorto approved these changes

2023-05-31 21:30 UTC, NicoCagnina requested changes

2023-05-31 23:15 UTC, Emanuel-Lamberti commented
Comments in the files have already been removed, and conflicts resolved.

2023-06-02 00:06 UTC, NicoCagnina approved these changes

2023-06-02 13:36 UTC, merged